export default class CommonConstants {

  static readonly TAG_NAME: string = 'yaoxiaowen'

  /**
   * The index page message.
   */
  static readonly IDNEX_MESAGE: string = 'Index Page';
  /**
   * The src msg.
   */
  static readonly SECOND_SRC_MSG: string = 'Index页面传来的数据';
  /**
   * The second page url.
   */
  static readonly SECOND_URL: string = 'pages/SecondPage';
  /**
   * The second page message.
   */
  static readonly SECOND_MESSAGE: string = 'Second Page';
  /**
   * The src param.
   */
  static readonly SECOND_SRC_PARAM: string = 'src';
  /**
   * Full the width.
   */
  static readonly FULL_WIDTH: string = '100%';
  /**
   * Full the height.
   */
  static readonly FULL_HEIGHT: string = '100%';
  /**
   * The hello world font size.
   */
  static readonly FONT_SIZE: string = '38fp';
  /**
   * The param font size.
   */
  static readonly PARAMS_FONT_SIZE: string = '20fp';
  /**
   * The button font size.
   */
  static readonly BUTTON_FONT_SIZE: string = '16fp';
  /**
   * The button width.
   */
  static readonly BUTTON_WIDTH: string = '296vp';
  /**
   * The button height.
   */
  static readonly BUTTON_HEIGHT: string = '40vp';
  /**
   * The layout height.
   */
  static readonly LAYOUT_HEIGHT: string = '140vp';
  /**
   * The param opacity.
   */
  static readonly PARAMS_OPACITY: number = 0.6;
}